### ISSUE TITLE
Behavior of IDEBuildOperationTimingLogLevel

### ISSUE THREAD

**Issue by odnoletkov** [ctreffs/xcode-defaults#6]
> Enable extensive per operation timing logs
> 
> defaults write com.apple.dt.Xcode IDEBuildOperationTimingLogLevel -int 3

Can you explain what this actually affects? Turing on and off I can't see any difference.

**Comment by ctreffs** [comment]
This seems to be a deprecated/unused settings - could not find any references to this and could not verify it working (anymore). Removed with PR https://github.com/ctreffs/xcode-defaults/pull/7
